### ISSUE TITLE
Criar guia em Markdown

### ISSUE THREAD

**Issue by PedroVNasc** [runcodes-icmc/guides#1]
Acho que seria interessante que tivesse o guia em Markdown ao invés de manter no txt.

Eu tenho experiência com Markdown e posso fazer o README com o tutorial.

Também tem alguns pequenos erros ortográficos e na parte de clonar o repositório, eu não consegui clonar da forma como estava indicando, seria interessante mudar para clonagem através do link direto.

**Comment by LiviaLelis** [comment]
Adicionado um primeiro guia em Markdown com as instruções corrigidas para deploy de produção, ainda existem algumas ideias de guias adicionais a serem desenvolvidos que deixei apontado nos arquivos.
