### ISSUE TITLE
Erro com banco de dados

### ISSUE THREAD

**Issue by silvaphl** [runcodes-icmc/guides#3]
Olá, estou executando o guia "RuncodesInstall_SingleMachine.txt", todavia estou com um erro.

Ao verificar o log, tenho o seguinte:

```
server-database-1  | 2023-09-22 01:23:25.872 UTC [88] FATAL:  password authentication failed for user "runcodes"
server-database-1  | 2023-09-22 01:23:25.872 UTC [88] DETAIL:  User "runcodes" has no password assigned.
server-database-1  | 	Connection matched pg_hba.conf line 99: "host all all all md5"
```

Alguma sugestão de como corrigir ou onde errei?

**Comment by LiviaLelis** [comment]
Opa. Então, não recomendo seguir este guia, ele está desatualizado em comparação com o principal, já que o deploy final acaba não sendo muito adequado para produção.

De todo modo, não consegui reproduzir aqui o problema indicado. Foi feita alguma modificação nos arquivos?

**Comment by silvaphl** [comment]
Bom dia, @DanielHLelis.
Muito obrigado pela resposta.

Já troquei para o tutorial de deployment.
